---
- name: Get the hostname
  command: hostname --fqdn
  register: hostname_fqdn

- name: Print the hostname
  debug:
    var: hostname_fqdn

- name: Get the OS
  shell: source /etc/os-release && echo $NAME
  register: os_distribution

- name: Print the OS
  debug:
    var: os_distribution

- name: Get the OS version
  shell: source /etc/os-release && echo $VERSION_ID
  register: os_version

- name: Print the OS version
  debug:
    var: os_version

- name: Get the IPv4 address
  command: ip -f inet addr show eth0 | grep -Po 'inet \K[\d.]+'
  register: ipv4_address

- name: Print the IPv4 address
  debug:
    var: ipv4_address

- name: Get the local users in /etc/passwd
  command: cat /etc/passwd
  register: passwd

- name: Print the contents of /etc/passwd
  debug:
    var: passwd

- name: Gather the apt package facts
  command: apt list --installed
  register: packages

- name: Print the apt package facts
  debug:
    var: packages

- name: Get the software that is run at startup
  command: ls /etc/init.d
  register: initd_contents

- name: Print the startup software
  debug:
    var: initd_contents

- name: Get all systemd services
  command: ls -l /lib/systemd/system/*.service /etc/systemd/system/*.service
  register: systemd_services

- name: Print the systemd services
  debug:
    var: systemd_services

- name: Get user login history
  command: last
  register: login_history

- name: Print the login history
  debug:
    var: login_history

- name: Get running processes
  command: ps aux
  register: running_processes

- name: Print running processes
  debug:
    var: running_processes
