- hosts: windows
  tasks:

    - name: Query Windows Using OSQuery
    - service: name=winosquery
    - win_command: osqueryi "SELECT hostnames FROM system_info;"
    - win_command: osqueryi "SELECT name FROM ntdomain;"
    - win_command: osqueryi "SELECT name,version FROM os_version;"
    - win_command: osqueryi 'SELECT address,friendly_name FROM interface_addresses WHERE friendly_name LIKE "%Wi-Fi%" OR friendly_name LIKE "Ethernet%";'
    - win_command: osqueryi "SELECT username FROM users;"
    - win_command: osqueryi "SELECT * FROM etc_services;"
    - win_command: osqueryi "SELECT * FROM programs;"
    - win_command: osqueryi "SELECT * FROM startup_items;"
    - win_command: osqueryi "SELECT * FROM logon_sessions;"
    - win_command: osqueryi 'SELECT pid,name,path,cmdline FROM processes WHERE state="STILL_ACTIVE";'
    - win_command: osqueryi 'SELECT s.pid,p.name,remote_address,family,protocol,remote_port FROM process_open_sockets s JOIN processes p on s.pid = p.pid WHERE remote_port NOT IN (80, 443) AND family = 2;'
    
